
{{ if .Values.admin_password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin-password
  namespace: {{ .Release.Namespace | quote }}
stringData:
  password: {{ .Values.admin_password }}
{{ end }}
